services:
  frontend:
    image: angelolmg/controleimpressao-frontend:v2.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: angelolmg/controleimpressao-backend:v2.0
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - archives_volume:/app/archives/
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  archives_volume:
  postgres_data: